import type { Issue, User, Verification, Comment, TimelineEvent } from "./types";

/**
 * Seed data — two demo clusters so the map is alive in recognizable places:
 *   • Indiranagar, Bengaluru  (~12.97 N, 77.64 E)
 *   • Cyber City / Gurugram   (~28.49 N, 77.08 E)
 * Everywhere else intentionally has no reports (the UI shows a "be the first to
 * report" empty state), so location filtering feels real.
 */

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

export const SEED_USERS: User[] = [
  {
    id: "u_demo",
    name: "You (Demo)",
    role: "citizen",
    points: 240,
    badges: ["First Report", "Sharp Eye"],
    ward: "Indiranagar",
    created_at: daysAgo(30),
  },
  {
    id: "u_priya",
    name: "Priya Sharma",
    role: "citizen",
    points: 1820,
    badges: ["Top Contributor", "Civic Star", "Sharp Eye"],
    ward: "Indiranagar",
    created_at: daysAgo(120),
  },
  {
    id: "u_arjun",
    name: "Arjun Mehta",
    role: "citizen",
    points: 940,
    badges: ["Fast Responder"],
    ward: "Gurugram",
    created_at: daysAgo(80),
  },
  {
    id: "u_kavya",
    name: "Kavya Reddy",
    role: "citizen",
    points: 410,
    badges: ["First Report"],
    ward: "Gurugram",
    created_at: daysAgo(45),
  },
  {
    id: "u_authority",
    name: "Ward Office",
    role: "authority",
    points: 0,
    badges: [],
    ward: "Indiranagar",
    created_at: daysAgo(200),
  },
];

export const SEED_ISSUES: Issue[] = [
  // ───── Indiranagar, Bengaluru ─────
  {
    id: "iss_001",
    title: "Deep pothole on 100 Feet Road",
    description:
      "Large pothole near the bus stop, dangerous for two-wheelers at night. Has been growing over the last week.",
    category_id: "pothole",
    severity: 5,
    lat: 12.9784,
    lng: 77.6408,
    location_name: "100 Feet Rd, Indiranagar",
    ward: "Indiranagar",
    status: "verified",
    image_url: "/img/pothole.jpg",
    reporter_id: "u_priya",
    reporter_name: "Priya Sharma",
    trust_score: 0.88,
    confirm_count: 14,
    deny_count: 0,
    created_at: hoursAgo(20),
    updated_at: hoursAgo(3),
    resolved_at: null,
  },
  {
    id: "iss_002",
    title: "Garbage not collected for 4 days",
    description:
      "Overflowing bin near the market, smell and flies. Needs urgent pickup.",
    category_id: "garbage",
    severity: 3,
    lat: 12.9702,
    lng: 77.6429,
    location_name: "Indiranagar Market",
    ward: "Indiranagar",
    status: "verified",
    image_url: "/img/garbage.jpg",
    reporter_id: "u_priya",
    reporter_name: "Priya Sharma",
    trust_score: 0.92,
    confirm_count: 21,
    deny_count: 0,
    created_at: daysAgo(1),
    updated_at: hoursAgo(2),
    resolved_at: null,
  },
  {
    id: "iss_003",
    title: "Exposed live wire, dangerous",
    description:
      "Broken junction box with exposed wires at chest height. Extremely dangerous.",
    category_id: "electric",
    severity: 5,
    lat: 12.9762,
    lng: 77.6459,
    location_name: "CMH Rd Junction, Indiranagar",
    ward: "Indiranagar",
    status: "verified",
    image_url: "/img/electric.jpg",
    reporter_id: "u_priya",
    reporter_name: "Priya Sharma",
    trust_score: 0.95,
    confirm_count: 31,
    deny_count: 0,
    created_at: hoursAgo(10),
    updated_at: hoursAgo(1),
    resolved_at: null,
  },
  {
    id: "iss_004",
    title: "Streetlight out on 12th Main",
    description: "Entire stretch dark at night, safety concern for pedestrians.",
    category_id: "streetlight",
    severity: 3,
    lat: 12.9758,
    lng: 77.6381,
    location_name: "12th Main Rd, Indiranagar",
    ward: "Indiranagar",
    status: "in_progress",
    image_url: "/img/streetlight.jpg",
    reporter_id: "u_arjun",
    reporter_name: "Arjun Mehta",
    trust_score: 0.74,
    confirm_count: 7,
    deny_count: 1,
    created_at: daysAgo(3),
    updated_at: hoursAgo(12),
    resolved_at: null,
  },

  // ───── Cyber City / Gurugram ─────
  {
    id: "iss_005",
    title: "Burst water pipe, waterlogging",
    description: "Pipe burst outside the office complex, water pooling on the road.",
    category_id: "water_leak",
    severity: 4,
    lat: 28.4690,
    lng: 77.0628,
    location_name: "Sector 29, Gurugram",
    ward: "Gurugram",
    status: "reported",
    image_url: "/img/water_leak.jpg",
    reporter_id: "u_kavya",
    reporter_name: "Kavya Reddy",
    trust_score: 0.61,
    confirm_count: 3,
    deny_count: 0,
    created_at: hoursAgo(6),
    updated_at: hoursAgo(6),
    resolved_at: null,
  },
  {
    id: "iss_006",
    title: "Drain overflow near the metro",
    description:
      "Drain overflowing onto the road after rain. Health hazard for commuters.",
    category_id: "drainage",
    severity: 5,
    lat: 28.4530,
    lng: 77.1010,
    location_name: "Golf Course Rd, Gurugram",
    ward: "Gurugram",
    status: "in_progress",
    image_url: "/img/drainage.jpg",
    reporter_id: "u_kavya",
    reporter_name: "Kavya Reddy",
    trust_score: 0.79,
    confirm_count: 17,
    deny_count: 0,
    created_at: daysAgo(4),
    updated_at: hoursAgo(20),
    resolved_at: null,
  },
  {
    id: "iss_007",
    title: "Fallen tree blocking the path",
    description: "Tree came down after the storm and is blocking the footpath, branches spilling onto the road.",
    category_id: "tree",
    severity: 4,
    lat: 28.4830,
    lng: 77.0980,
    location_name: "DLF Phase 2, Gurugram",
    ward: "Gurugram",
    status: "resolved",
    image_url: "/img/tree.jpg",
    reporter_id: "u_arjun",
    reporter_name: "Arjun Mehta",
    trust_score: 0.83,
    confirm_count: 9,
    deny_count: 0,
    created_at: daysAgo(8),
    updated_at: daysAgo(5),
    resolved_at: daysAgo(5),
  },
  {
    id: "iss_008",
    title: "Road sign damaged and unreadable",
    description: "Direction sign weathered and faded, leaning on bent posts — text no longer readable.",
    category_id: "signage",
    severity: 2,
    lat: 28.4949,
    lng: 77.0869,
    location_name: "Cyber Hub, Gurugram",
    ward: "Gurugram",
    status: "resolved",
    image_url: "/img/signage.jpg",
    reporter_id: "u_arjun",
    reporter_name: "Arjun Mehta",
    trust_score: 0.71,
    confirm_count: 5,
    deny_count: 0,
    created_at: daysAgo(15),
    updated_at: daysAgo(10),
    resolved_at: daysAgo(10),
  },
];

export const SEED_VERIFICATIONS: Verification[] = [
  {
    id: "ver_001",
    issue_id: "iss_001",
    user_id: "u_arjun",
    user_name: "Arjun Mehta",
    type: "confirm",
    created_at: hoursAgo(18),
  },
  {
    id: "ver_002",
    issue_id: "iss_001",
    user_id: "u_kavya",
    user_name: "Kavya Reddy",
    type: "confirm",
    created_at: hoursAgo(15),
  },
];

export const SEED_TIMELINE: TimelineEvent[] = [
  {
    id: "tl_001",
    issue_id: "iss_001",
    status: "reported",
    note: "Issue reported with photo",
    by_user: "Priya Sharma",
    created_at: hoursAgo(20),
  },
  {
    id: "tl_002",
    issue_id: "iss_001",
    status: "verified",
    note: "Reached 14 community confirmations",
    by_user: "System",
    created_at: hoursAgo(3),
  },
];

export const SEED_COMMENTS: Comment[] = [
  {
    id: "c_001",
    issue_id: "iss_001",
    user_id: "u_arjun",
    user_name: "Arjun Mehta",
    text: "I can confirm, I ride past this every day. It's getting worse.",
    created_at: hoursAgo(17),
  },
  {
    id: "c_002",
    issue_id: "iss_003",
    user_id: "u_kavya",
    user_name: "Kavya Reddy",
    text: "Please prioritise this — kids walk past it on the way to school.",
    created_at: hoursAgo(9),
  },
];

/** All seed tables, for the local store to hydrate from. */
export const SEED_DATA = {
  users: SEED_USERS,
  issues: SEED_ISSUES,
  verifications: SEED_VERIFICATIONS,
  timeline: SEED_TIMELINE,
  comments: SEED_COMMENTS,
};
